using aspnet_gameapi.Data;
using aspnet_gameapi.Endpoints;
using aspnet_gameapi.Models;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddValidation();
builder.AddGamesStoreDb();
var app = builder.Build();
app.MapGamesEndpoints();
app.MigrateDb();
app.Run();